services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d abrasci -U abrasci"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
